#!/bin/sh

# PROVIDE: wgu
# REQUIRE: LOGIN

. /etc/rc.subr

name="wgu"

procname="/usr/local/bin/${name}"
desc="${name}"
rcvar="${name}_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-u _${name} -T ${name} -p ${pidfile} -- ${procname} -A -config /etc/wgu/wgu.conf -t"

load_rc_config $name
run_rc_command "$@"
